#!/bin/sh
#
# Automatic adaption of version and the readme files. To enable these
# hooks execute
#
#   echo -e '#!/bin/sh\n\nexec misc/git-pre-commit' > .git/hooks/pre-commit
#   echo -e '#!/bin/sh\n\nexec misc/git-post-commit' > .git/hooks/post-commit
#   chmod +x .git/hooks/{pre-commit,post-commit}
#
# in the git root directory.


if [ -a .commit ]
then
    rm .commit
    
    # Update version number
    curver=`cat syfco.cabal | grep '^version' | sed 's/^version:[^.]*.[^.]*.[^.]*.\([0-9]*\).*/\1/'`
    newver=`expr $curver + 1`
    
    sed -i "s/\(^version:[^.]*.[^.]*.[^.]*.\)[0-9]*/\1$newver/" syfco.cabal

    # build
    cabal configure
    
    if ! [[ $? = 0 ]]
    then
        # Reset version
        sed -i "s/\(^version:[^.]*.[^.]*.[^.]*.\)[0-9]*/\1$oldver/" syfco.cabal
        exit 1
    fi

    # build
    cabal build
    
    if ! [[ $? = 0 ]]
    then
        # Reset version
        sed -i "s/\(^version:[^.]*.[^.]*.[^.]*.\)[0-9]*/\1$oldver/" syfco.cabal
        exit 1
    fi

    dist/build/syfco/syfco --readme > README
    dist/build/syfco/syfco --readme.md > README.md

    git commit -a --amend -C HEAD --no-verify
fi
exit
